// src/components/svelte/WebConsole.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy, onMount } from "svelte";
  import { kernel } from "../../core/Kernel.js";
  import type { IConsole } from "../../interfaces/IConsole.interface.js";
  import type { CommandResult } from "../../types/index.js";

  // Props
  export let prompt: string = "$ ";
  export let width: string | number = "100%";
  export let height: string | number = 400;
  export let theme: string = "default";
  export let workingDirectory: string = "/home/user";

  // Events
  const dispatch = createEventDispatcher<{
    command: { command: string; result: CommandResult };
    ready: IConsole;
    error: Error;
  }>();

  // Local state
  let container: HTMLDivElement;
  let webConsoleElement: HTMLElement | null = null;
  let consoleInstance: IConsole | null = null;

  // Reactive statements
  $: if (webConsoleElement && theme) {
    webConsoleElement.setAttribute("theme", theme);
  }

  $: if (webConsoleElement && prompt) {
    webConsoleElement.setAttribute("prompt", prompt);
  }

  async function initializeConsole() {
    try {
      if (!kernel.isStarted) {
        await kernel.start();
      }

      webConsoleElement = document.createElement("web-console");
      webConsoleElement.setAttribute("prompt", prompt);
      webConsoleElement.setAttribute("theme", theme);
      webConsoleElement.style.width =
        typeof width === "number" ? `${width}px` : width;
      webConsoleElement.style.height =
        typeof height === "number" ? `${height}px` : height;

      // Event-Listener
      webConsoleElement.addEventListener("command", (event: Event) => {
        const customEvent = event as CustomEvent;
        dispatch("command", customEvent.detail);
      });

      webConsoleElement.addEventListener("ready", (event: Event) => {
        const customEvent = event as CustomEvent;
        consoleInstance = customEvent.detail;
        dispatch("ready", customEvent.detail);
      });

      webConsoleElement.addEventListener("error", (event: Event) => {
        const customEvent = event as CustomEvent;
        dispatch("error", customEvent.detail);
      });

      container.appendChild(webConsoleElement);
    } catch (error) {
      dispatch("error", error as Error);
    }
  }

  // Public API functions
  export async function executeCommand(
    command: string,
  ): Promise<CommandResult | null> {
    if (consoleInstance) {
      return await consoleInstance.execute(command);
    }
    return null;
  }

  export function clear(): void {
    if (webConsoleElement && "clear" in webConsoleElement) {
      (webConsoleElement as any).clear();
    }
  }

  export function setPrompt(newPrompt: string): void {
    prompt = newPrompt;
  }

  export function setTheme(newTheme: string): void {
    theme = newTheme;
  }

  onMount(() => {
    initializeConsole();
  });

  onDestroy(() => {
    if (webConsoleElement && webConsoleElement.parentNode) {
      webConsoleElement.parentNode.removeChild(webConsoleElement);
    }
    if (consoleInstance) {
      kernel.destroyConsole(consoleInstance.id);
    }
  });
</script>

<div bind:this={container} class="svelte-web-console-container"></div>

<style>
  .svelte-web-console-container {
    width: 100%;
    height: 100%;
    display: block;
  }
</style>

// src/components/angular/WebConsole.component.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
  ViewChild,
} from "@angular/core";
import { kernel } from "../../core/Kernel.js";
import type { IConsole } from "../../interfaces/IConsole.interface.js";
import type { CommandResult } from "../../types/index.js";

@Component({
  selector: "web-console",
  template: `<div #container class="angular-web-console-container"></div>`,
  styles: [
    `
      .angular-web-console-container {
        width: 100%;
        height: 100%;
        display: block;
      }
    `,
  ],
})
export class WebConsoleComponent implements OnInit, OnDestroy {
  @Input() prompt: string = "$ ";
  @Input() width: string | number = "100%";
  @Input() height: string | number = 400;
  @Input() theme: string = "default";
  @Input() workingDirectory: string = "/home/user";

  @Output() command = new EventEmitter<{
    command: string;
    result: CommandResult;
  }>();
  @Output() ready = new EventEmitter<IConsole>();
  @Output() error = new EventEmitter<Error>();

  @ViewChild("container", { static: true }) containerRef!: ElementRef;

  private element: HTMLElement | null = null;
  private consoleInstance: IConsole | null = null;

  async ngOnInit() {
    try {
      await this.initializeConsole();
    } catch (err) {
      this.error.emit(err as Error);
    }
  }

  ngOnDestroy() {
    if (this.element && this.element.parentNode) {
      this.element.parentNode.removeChild(this.element);
    }
    if (this.consoleInstance) {
      kernel.destroyConsole(this.consoleInstance.id);
    }
  }

  private async initializeConsole() {
    if (!kernel.isStarted) {
      await kernel.start();
    }

    this.element = document.createElement("web-console");
    this.element.setAttribute("prompt", this.prompt);
    this.element.setAttribute("theme", this.theme);
    this.element.style.width =
      typeof this.width === "number" ? `${this.width}px` : this.width;
    this.element.style.height =
      typeof this.height === "number" ? `${this.height}px` : this.height;

    // Event-Listener
    this.element.addEventListener("command", (event: Event) => {
      const customEvent = event as CustomEvent;
      this.command.emit(customEvent.detail);
    });

    this.element.addEventListener("ready", (event: Event) => {
      const customEvent = event as CustomEvent;
      this.consoleInstance = customEvent.detail;
      this.ready.emit(customEvent.detail);
    });

    this.element.addEventListener("error", (event: Event) => {
      const customEvent = event as CustomEvent;
      this.error.emit(customEvent.detail);
    });

    this.containerRef.nativeElement.appendChild(this.element);
  }

  // Public API
  public async executeCommand(command: string): Promise<CommandResult | null> {
    if (this.consoleInstance) {
      return await this.consoleInstance.execute(command);
    }
    return null;
  }

  public clear(): void {
    if (this.element && "clear" in this.element) {
      (this.element as HTMLElement & { clear(): void }).clear();
    }
  }

  public setPrompt(newPrompt: string): void {
    this.prompt = newPrompt;
    if (this.element) {
      this.element.setAttribute("prompt", newPrompt);
    }
  }

  public setTheme(newTheme: string): void {
    this.theme = newTheme;
    if (this.element) {
      this.element.setAttribute("theme", newTheme);
    }
  }
}
