// src/components/vue/WebConsole.vue
<template>
  <div ref="container" class="vue-web-console-container"></div>
</template>

<script lang="ts">
import { defineComponent, onMounted, onUnmounted, ref, watch } from "vue";
import { kernel } from "../../core/Kernel.js";
import type { IConsole } from "../../interfaces/IConsole.interface.js";

export default defineComponent({
  name: "WebConsole",
  props: {
    prompt: { type: String, default: "$ " },
    width: { type: [String, Number], default: "100%" },
    height: { type: [String, Number], default: 400 },
    theme: { type: String, default: "default" },
    workingDirectory: { type: String, default: "/home/user" },
  },
  emits: ["command", "ready", "error"],
  setup(props, { emit }) {
    const container = ref<HTMLElement | null>(null);
    let webConsoleElement: HTMLElement | null = null;
    let consoleInstance: IConsole | null = null;

    const initializeConsole = async () => {
      try {
        if (!kernel.isStarted) {
          await kernel.start();
        }

        // Erstelle WebConsole Element
        webConsoleElement = document.createElement("web-console");
        webConsoleElement.setAttribute("prompt", props.prompt);
        webConsoleElement.setAttribute("theme", props.theme);
        webConsoleElement.style.width =
          typeof props.width === "number" ? `${props.width}px` : props.width;
        webConsoleElement.style.height =
          typeof props.height === "number" ? `${props.height}px` : props.height;

        // Add event listener
        webConsoleElement.addEventListener("command", (event: Event) => {
          const customEvent = event as CustomEvent;
          emit("command", customEvent.detail);
        });

        webConsoleElement.addEventListener("ready", (event: Event) => {
          const customEvent = event as CustomEvent;
          consoleInstance = customEvent.detail;
          emit("ready", customEvent.detail);
        });

        webConsoleElement.addEventListener("error", (event: Event) => {
          const customEvent = event as CustomEvent;
          emit("error", customEvent.detail);
        });

        // Add to DOM
        if (container.value) {
          container.value.appendChild(webConsoleElement);
        }
      } catch (error) {
        emit("error", error);
      }
    };

    // Watch for theme changes
    watch(
      () => props.theme,
      (newTheme) => {
        if (webConsoleElement) {
          webConsoleElement.setAttribute("theme", newTheme);
        }
      },
    );

    // Watch for prompt changes
    watch(
      () => props.prompt,
      (newPrompt) => {
        if (webConsoleElement) {
          webConsoleElement.setAttribute("prompt", newPrompt);
        }
      },
    );

    onMounted(() => {
      initializeConsole();
    });

    onUnmounted(() => {
      if (webConsoleElement && webConsoleElement.parentNode) {
        webConsoleElement.parentNode.removeChild(webConsoleElement);
      }
      if (consoleInstance) {
        kernel.destroyConsole(consoleInstance.id);
      }
    });

    // Public API
    const executeCommand = async (command: string) => {
      if (consoleInstance) {
        return await consoleInstance.execute(command);
      }
      return null;
    };

    const clear = () => {
      if (webConsoleElement && "clear" in webConsoleElement) {
        (webConsoleElement as any).clear();
      }
    };

    const setPrompt = (newPrompt: string) => {
      if (webConsoleElement) {
        webConsoleElement.setAttribute("prompt", newPrompt);
      }
    };

    return {
      container,
      executeCommand,
      clear,
      setPrompt,
    };
  },
});
</script>

<style scoped>
.vue-web-console-container {
  width: 100%;
  height: 100%;
  display: block;
}
</style>

// src/components/svelte/WebConsole.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy, onMount } from "svelte";
  import { kernel } from "../../core/Kernel.js";
  import type { IConsole } from "../../interfaces/IConsole.interface.js";
  import type { CommandResult } from "../../types/index.js";

  // Props
  export let prompt: string = "$ ";
  export let width: string | number = "100%";
  export let height: string | number = 400;
  export let theme: string = "default";
  export let workingDirectory: string = "/home/user";

  // Events
  const dispatch = createEventDispatcher<{
    command: { command: string; result: CommandResult };
    ready: IConsole;
    error: Error;
  }>();

  // Local state
  let container: HTMLDivElement;
  let webConsoleElement: HTMLElement | null = null;
  let consoleInstance: IConsole | null = null;

  // Reactive statements
  $: if (webConsoleElement && theme) {
    webConsoleElement.setAttribute("theme", theme);
  }

  $: if (webConsoleElement && prompt) {
    webConsoleElement.setAttribute("prompt", prompt);
  }

  async function initializeConsole() {
    try {
      if (!kernel.isStarted) {
        await kernel.start();
      }

      webConsoleElement = document.createElement("web-console");
      webConsoleElement.setAttribute("prompt", prompt);
      webConsoleElement.setAttribute("theme", theme);
      webConsoleElement.style.width =
        typeof width === "number" ? `${width}px` : width;
      webConsoleElement.style.height =
        typeof height === "number" ? `${height}px` : height;

      // Event-Listener
      webConsoleElement.addEventListener("command", (event: Event) => {
        const customEvent = event as CustomEvent;
        dispatch("command", customEvent.detail);
      });

      webConsoleElement.addEventListener("ready", (event: Event) => {
        const customEvent = event as CustomEvent;
        consoleInstance = customEvent.detail;
        dispatch("ready", customEvent.detail);
      });

      webConsoleElement.addEventListener("error", (event: Event) => {
        const customEvent = event as CustomEvent;
        dispatch("error", customEvent.detail);
      });

      container.appendChild(webConsoleElement);
    } catch (error) {
      dispatch("error", error as Error);
    }
  }

  // Public API functions
  export async function executeCommand(
    command: string,
  ): Promise<CommandResult | null> {
    if (consoleInstance) {
      return await consoleInstance.execute(command);
    }
    return null;
  }

  export function clear(): void {
    if (webConsoleElement && "clear" in webConsoleElement) {
      (webConsoleElement as any).clear();
    }
  }

  export function setPrompt(newPrompt: string): void {
    prompt = newPrompt;
  }

  export function setTheme(newTheme: string): void {
    theme = newTheme;
  }

  onMount(() => {
    initializeConsole();
  });

  onDestroy(() => {
    if (webConsoleElement && webConsoleElement.parentNode) {
      webConsoleElement.parentNode.removeChild(webConsoleElement);
    }
    if (consoleInstance) {
      kernel.destroyConsole(consoleInstance.id);
    }
  });
</script>

<div bind:this={container} class="svelte-web-console-container"></div>

<style>
  .svelte-web-console-container {
    width: 100%;
    height: 100%;
    display: block;
  }
</style>
